server:
  port: 8762
spring:
  application:
    # 当前服务注册在eureka-server上的名称
    name: configserver-native

 # 配置文件的读取方式，native表示本地读取
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # 将配置文件放在本地路径的shared文件夹中，classpath：指的是当前的classpath路径下
          search-locations: classpath:/shared