server:
  port: 8888
spring:
  application:
    # 当前服务注册在eureka-server上的名称
    name: configserver-remote

  cloud:
    config:
      server:
        git:
          # 远程仓库的地址
          uri: https://github.com/codezuo/springcloud.git
          # 远程仓库的配置文件的路径，这里为springcloud下对的config文件夹
          search-paths: config
          username: zuojun
          password: 98678678678zj
        default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/